 export const listSongs = [
  {
    id: 0,
    name: "Interstelar",
    artist: "Alexia",
    duration: "3:22",
    src: "./songs/Alexia-Interstelar.mp3",
    img: "./images/Alexia-Interstelar.jpg",
  },
  {
    id: 1,
    name: "Arata-mi",
    artist: "Alina Eremia",
    duration: "2:52",
    src: "./songs/AlinaEremia-Arata-mi.mp3",
    img: "./images/AlinaEremia-Arata-mi.jpg",
  },
  {
    id: 2,
    name: "Sa fii fericit",
    artist: "Alina Eremia",
    duration: "2:42",
    src: "./songs/AlinaEremia-SaFiiFericit.mp3",
    img: "./images/AlinaEremia-SaFiiFericit.jpg",
  },
  {
    id: 3,
    name: "Scrie-mi orice",
    artist: "Andia",
    duration: "3:27",
    src: "./songs/Andia-Scrie-miOrice.mp3",
    img: "./images/Andia-Scrie-miOrice.jpg",
  },
  {
    id: 4,
    name: "Ultima data",
    artist: "Emaa",
    duration: "3:35",
    src: "./songs/Emaa-UltimaData.mp3",
    img: "./images/Emaa-UltimaData.jpg",
  },
  {
    id: 5,
    name: "Closer To Christmas",
    artist: "Jason Derulo",
    duration: "3:10",
    src: "./songs/JasonDerulo-CloseToChristmas.mp3",
    img: "./images/JasonDerulo-CloseToChristmas.jpg",
  },
  {
    id: 6,
    name: "Pana imbatranim",
    artist: "Olivia Addams",
    duration: "3:21",
    src: "./songs/OliviaAddams-PanaImbatranim.mp3",
    img: "./images/OliviaAddams-PanaImbatranim.jpg",
  },
  {
    id: 7,
    name: "Un minut",
    artist: "Misha Miller",
    duration: "3:07",
    src: "./songs/MishaMiller-UnMinut.mp3",
    img: "./images/MishaMiller-UnMinut.jpg",
  },
  {
    id: 8,
    name: "Nu te mai astept",
    artist: "Alina Eremia",
    duration: "3:04",
    src: "./songs/AlinaEremia-NuTeMaiAstept.mp3",
    img: "./images/AlinaEremia-NuTeMaiAstept.jpg",
  },
  {
    id: 9,
    name: "Bailando Bachata",
    artist: "Chayanne",
    duration: "2:49",
    src: "./songs/Chayanne-Bailando-Bachata.mp3",
    img: "./images/Chayanne-Bailando-Bachata.jpg",
  }
];